### ISSUE TITLE
epcyp経由でIINAを起動するとドックに複数のアイコンが表示される

### ISSUE THREAD

**Issue by ArthurHandke** [mrhorin/epcyp#42]
epcypの再生プレイヤーをIINAに設定しすると、配信を開くたびにドックにアイコンが増える。
同じアプリなら複数のインスタンスを起動しても一つのアイコンに収まって欲しい。
これは、例えばPeerCastStation内蔵のチャンネルブラウザから.m3uファイルをダウンロードしてIINAで開くと上の通りの動作をするので、epcyp固有の現象だと思う。

**Comment by mrhorin** [comment]
複数の配信を同時視聴できるようにするため、mac環境ではプレイヤーを起動する時はopenコマンドの-nオプションで毎回新規インスタンスを起動するようにしています。
新規インスタンスを起動するとドックにインスタンスの数だけアイコンが表示されるのはOS側の仕様のような気がするのですが回避策はあるのでしょうか？
試しにFinderでプレイリストファイルからIINAで再生をしてみましたが、1つめの配信を開いてから別の2つめの配信のプレイリストファイルを開くと2つめの配信も1つめと同じインスタンスで再生されるため、必然的に1つめの配信の再生が停止して代わりに2つめの配信が再生されました。当然、この場合はインスタンスは1つなのでドック上のIINAのアイコンも1つしか表示されません。
