### ISSUE TITLE
「更新できませんでした」通知はいらないと思う

### ISSUE THREAD

**Issue by ArthurHandke** [mrhorin/epcyp#45]

**Comment by mrhorin** [comment]
OSの通知機能以外で他に更新の失敗を視覚的に知らせる方法が思い浮かばなかったのと、PecaRecorderが更新失敗時に通知をしていたのでそれに合わせました。
さすがに更新失敗時に何も知らせないのはUX的に問題があると思うので、他に何か良い案があれば提案してみてください。
